[tool.poetry]
name = "data-retrieval"
version = "0.1.0"
description = ""
authors = ["Andres-ubuntu <andrescamp_ac@hotmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
notebook = "^7.3.1"
pandas = "^2.2.3"
ipykernel = "^6.29.5"


[tool.poetry.group.dev.dependencies]
ipykernel = "^6.29.5"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
